"""
Builds a single employee's Payslip PDF for one Pay Register period, laid out to match
the org's existing payslip template (company header, employee/attendance info block,
Earnings/Deductions table, net pay summary).

Two data sources feed it, matching how Payroll's data is now split across tabs:
- The Pay Register's own employee row (routers/payroll.py) — attendance + the
  Earnings/Deductions/Actual-Salary/Company-Contribution figures for that period.
- The Employees record (Job Details / Bank & Statutory Details / Employee Details tabs)
  — designation, pay mode, bank details, ESI No, email. `employee_doc` is None if the
  Pay Register's Code didn't match any Employee record (see payroll.py's
  employee_found flag) — those fields just render blank/N.A. in that case.
"""

import calendar
import os
from datetime import date
from io import BytesIO
from typing import Optional

from reportlab.lib import colors
from reportlab.lib.enums import TA_CENTER, TA_RIGHT
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.pdfbase import pdfmetrics
from reportlab.pdfbase.ttfonts import TTFont
from reportlab.platypus import (
    BaseDocTemplate, Frame, Image, PageTemplate, Paragraph, SimpleDocTemplate, Spacer, Table, TableStyle,
)

# Arimo (SIL Open Font License, bundled under app/assets/fonts/) — metrically compatible
# with Arial, matching the glyph widths of the org's reference payslip (generated by
# tx_pdf with embedded Arial) far more closely than reportlab's base-14 Helvetica, with
# no font-licensing concerns for redistribution/deployment.
_FONTS_DIR = os.path.join(os.path.dirname(__file__), "..", "assets", "fonts")
FONT_REGULAR, FONT_BOLD, FONT_ITALIC = "Arimo", "Arimo-Bold", "Arimo-Italic"
if FONT_REGULAR not in pdfmetrics.getRegisteredFontNames():
    pdfmetrics.registerFont(TTFont(FONT_REGULAR, os.path.join(_FONTS_DIR, "Arimo-Regular.ttf")))
    pdfmetrics.registerFont(TTFont(FONT_BOLD, os.path.join(_FONTS_DIR, "Arimo-Bold.ttf")))
    pdfmetrics.registerFont(TTFont(FONT_ITALIC, os.path.join(_FONTS_DIR, "Arimo-Italic.ttf")))
    pdfmetrics.registerFontFamily(FONT_REGULAR, normal=FONT_REGULAR, bold=FONT_BOLD, italic=FONT_ITALIC)

_MONTH_NAMES = [
    "", "January", "February", "March", "April", "May", "June",
    "July", "August", "September", "October", "November", "December",
]

_ONES = [
    "", "One", "Two", "Three", "Four", "Five", "Six", "Seven", "Eight", "Nine",
    "Ten", "Eleven", "Twelve", "Thirteen", "Fourteen", "Fifteen", "Sixteen",
    "Seventeen", "Eighteen", "Nineteen",
]
_TENS = ["", "", "Twenty", "Thirty", "Forty", "Fifty", "Sixty", "Seventy", "Eighty", "Ninety"]

# Earnings/Deductions line items shown on the payslip, in template order — each has a
# Pay Register "scale" (standard entitlement) key and an "_actual" (as paid) key. Rows
# where both are zero/blank are omitted, same as the reference payslip (e.g. ESI/TDS/
# Medical/Advance don't print for an employee who has none).
_EARNING_ITEMS = [
    ("basic_salary", "BASIC SALARY"), ("hra", "HRA"), ("cca", "CCA"),
    ("food_allowance", "FOOD ALLOWANCE"), ("transport_allowance", "TRANSPORT ALLOWANCE"),
    ("medical_allowances", "MEDICAL ALLOWANCES"), ("monthly_bonus", "MONTHLY BONUS"),
    ("performance_incentive", "PERFORMANCE INCENTIVE"), ("arrears", "ARREARS"),
    ("lta_ltc", "LTA/LTC"), ("business_bonus", "BUSINESS BONUS"),
]
_DEDUCTION_ITEMS = [
    ("professional_tax", "PROFESSIONAL TAX"), ("esi", "ESI"), ("provident_fund", "PROVIDENT FUND"),
    ("tds", "TDS"), ("medical", "MEDICAL"), ("advance", "ADVANCE"),
]


def _two_digit_words(n: int) -> str:
    if n < 20:
        return _ONES[n]
    tens, ones = divmod(n, 10)
    return (_TENS[tens] + (" " + _ONES[ones] if ones else "")).strip()


def _three_digit_words(n: int) -> str:
    if n >= 100:
        hundreds, rest = divmod(n, 100)
        return _ONES[hundreds] + " Hundred" + (" " + _two_digit_words(rest) if rest else "")
    return _two_digit_words(n)


def number_to_words_inr(amount) -> str:
    """Indian-numbering (crore/lakh/thousand) words for the rupee part of `amount`,
    e.g. 120000 -> 'One Lakh Twenty Thousand'. No 'Rupees'/'Only' wrapper — the caller
    adds those (see build_payslip_pdf's 'Rs. {words} Only' line)."""
    n = int(round(float(amount or 0)))
    if n == 0:
        return "Zero"
    crore, n = divmod(n, 1_00_00_000)
    lakh, n = divmod(n, 1_00_000)
    thousand, hundred = divmod(n, 1000)
    parts = []
    if crore:
        parts.append(_three_digit_words(crore) + " Crore")
    if lakh:
        parts.append(_three_digit_words(lakh) + " Lakh")
    if thousand:
        parts.append(_three_digit_words(thousand) + " Thousand")
    if hundred:
        parts.append(_three_digit_words(hundred))
    return " ".join(parts)


def _fmt(amount) -> str:
    return f"{float(amount or 0):,.2f}"


def _fmt_days(value) -> str:
    """Attendance figures (total_days, wk_off, ...) come through as floats — render
    whole-number counts ('30') instead of the raw float repr ('30.0')."""
    if value is None:
        return ""
    n = float(value)
    return str(int(n)) if n.is_integer() else str(n)


def _weekday_abbrs(weekdays) -> str:
    return ", ".join(calendar.day_abbr[d].upper() for d in sorted(set(weekdays or [])) if 0 <= d <= 6)


def _month_bounds(period: str):
    year, month = (int(x) for x in period.split("-"))
    last_day = calendar.monthrange(year, month)[1]
    return date(year, month, 1), date(year, month, last_day)


def _g(d: Optional[dict], key: str, default=None):
    return (d or {}).get(key) or default


# Content frame is a fixed 523.5pt wide (A4 width less 36pt/0.5in margins each side),
# matching the org's existing tx_pdf-generated payslip exactly — column widths below are
# taken directly off that reference rather than derived proportionally.
_CONTENT_WIDTH = 523.5
_LOGO_HEIGHT = 115.5
_INFO_COL_WIDTHS = [94.2, 193.7, 94.2, 141.4]
# One 8-column table, not two: [Earnings desc/scale/amount] [5.85+5.85pt gutter, split so
# a vertical rule can run through its middle] [Deductions desc/scale/amount]. Keeping it a
# single table (rather than two side-by-side ones) means Earnings/Deductions rows share
# one row-height per index — e.g. when TRANSPORT ALLOWANCE wraps to two lines, the
# Deductions side's blank filler row grows to match it, so "Total Earnings"/
# "Total Deductions" stay aligned on the reference's layout.
_ED_COL_WIDTHS = [116.3, 69.8, 69.8, 5.85, 5.85, 116.3, 69.8, 69.8]


def build_payslip_pdf(
    company_name: Optional[str],
    company_address: Optional[str],
    logo_bytes: Optional[bytes],
    period: str,
    row: dict,
    employee_doc: Optional[dict],
    weekly_off_days,
) -> bytes:
    buf = BytesIO()
    doc = SimpleDocTemplate(buf, pagesize=A4, topMargin=36, bottomMargin=36, leftMargin=36, rightMargin=36)
    # SimpleDocTemplate.build() hardcodes Frame(..., leftPadding=6, ...) and ignores any
    # *Padding kwargs passed to the constructor above, so the margins alone don't mark the
    # true content edge — every flowable would sit 6pt further in than intended (e.g. the
    # logo at 42pt from the top instead of 36pt). Building the frame ourselves with padding
    # zeroed out, then calling BaseDocTemplate.build directly, bypasses that override.
    frame = Frame(
        doc.leftMargin, doc.bottomMargin, doc.width, doc.height,
        leftPadding=0, bottomPadding=0, rightPadding=0, topPadding=0, id="normal",
    )
    doc.addPageTemplates([
        PageTemplate(id="First", frames=frame, pagesize=doc.pagesize),
        PageTemplate(id="Later", frames=frame, pagesize=doc.pagesize),
    ])

    styles = getSampleStyleSheet()
    center = ParagraphStyle("center", parent=styles["Normal"], alignment=TA_CENTER)
    company_style = ParagraphStyle("company", parent=center, fontName=FONT_BOLD, fontSize=9, leading=11)
    address_style = ParagraphStyle("address", parent=center, fontName=FONT_BOLD, fontSize=9, leading=11)
    title_style = ParagraphStyle("title", parent=center, fontName=FONT_BOLD, fontSize=11, leading=13, spaceBefore=-0.33)
    subtitle_style = ParagraphStyle("subtitle", parent=center, fontName=FONT_BOLD, fontSize=11, leading=13)
    footer_style = ParagraphStyle("footer", parent=styles["Normal"], fontName=FONT_BOLD, fontSize=9, leading=11)
    net_pay_style = ParagraphStyle("netPay", parent=styles["Normal"], fontName=FONT_BOLD, fontSize=9, leading=11)
    tds_style = ParagraphStyle("tds", parent=styles["Normal"], fontName=FONT_ITALIC, fontSize=9, leading=11)

    story = []

    if logo_bytes:
        try:
            img = Image(BytesIO(logo_bytes))
            # Pin height to the reference's 115.5pt and let width follow the source's own
            # aspect ratio — fitting-within-a-box (the previous approach) instead lets
            # whichever dimension is proportionally tighter win, which quietly shrinks the
            # height any time the uploaded logo's aspect ratio isn't exactly 2.905:1.
            img.drawHeight = _LOGO_HEIGHT
            img.drawWidth = _LOGO_HEIGHT * (img.imageWidth / img.imageHeight)
            img.hAlign = "CENTER"
            story.append(img)
            story.append(Spacer(1, 3))
        except Exception:
            pass  # a broken/unsupported logo image shouldn't block payslip generation

    if company_name:
        story.append(Paragraph(company_name, company_style))
    if company_address:
        # The org's title-block cell carries its own line break (street line vs
        # city/state line, see payroll.py's _detect_company_info) — preserved end to end
        # so it renders as separate lines instead of one auto-wrapped paragraph.
        for line in company_address.split("\n"):
            story.append(Paragraph(line, address_style))

    year, month = (int(x) for x in period.split("-"))
    month_start, month_end = _month_bounds(period)
    story.append(Paragraph(f"Pay Slip For the Month of {_MONTH_NAMES[month]}-{year}", title_style))
    story.append(Paragraph(f"(From {month_start.strftime('%d/%m/%Y')} To {month_end.strftime('%d/%m/%Y')})", subtitle_style))
    story.append(Spacer(1, 10.93))

    # ── Employee / attendance info block ──────────────────────────────────────────
    wk_off_label = _fmt_days(row.get("wk_off")) or "0"
    off_days = _weekday_abbrs(weekly_off_days)
    if off_days:
        wk_off_label += f" ({off_days})"

    info_rows = [
        ("Employee Name", row.get("name"), "Employee Code", row.get("code")),
        ("Father's Name", row.get("father_husband_name"), "DOJ", row.get("doj")),
        ("Bank A/c No.", _g(employee_doc, "account_no"), "ESI A/c No", _g(employee_doc, "esi_no", "N.A.")),
        ("Designation", _g(employee_doc, "designation"), "Bank Name", _g(employee_doc, "bank_name")),
        ("Pay Mode", _g(employee_doc, "pay_mode"), "Gender", row.get("gender")),
        ("E-Mail", _g(employee_doc, "email"), "", ""),
        ("Month Days", _fmt_days(row.get("total_days")), "Total Paid Days", _fmt_days(row.get("net_paid_days"))),
        ("Weekly-Off", wk_off_label, "Days-Off", 0),
        ("Paid Holidays", _fmt_days(row.get("holiday")), "Unpaid Holidays", 0),
        ("Working Days", _fmt_days(row.get("max_work_days")), "Max Payable Days", _fmt_days(row.get("max_payable_days"))),
        ("LWP", _fmt_days(row.get("absent_lwp")), "Net Paid Days", _fmt_days(row.get("net_paid_days"))),
        ("Present Days", _fmt_days(row.get("present_days")), "Paid Leaves", _fmt_days(row.get("total_leaves"))),
    ]
    # Reference has this backwards from what you'd expect: field labels stay regular
    # weight, and it's the values (everything after the colon) that are bold.
    info_label_style = ParagraphStyle("infoLabel", parent=styles["Normal"], fontName=FONT_REGULAR, fontSize=9, leading=9)
    info_value_style = ParagraphStyle("infoValue", parent=styles["Normal"], fontName=FONT_BOLD, fontSize=9, leading=9)

    def info_cell(text, bold=False):
        # Always a Paragraph, even for "" — a bare "" cell would fall back to Table's
        # default paragraph style (larger font/leading) and silently inflate that row's
        # height relative to its neighbors.
        return Paragraph(str(text), info_label_style if bold else info_value_style)

    info_table_data = [
        [
            info_cell(l1, bold=True), info_cell(f": {v1 if v1 is not None else ''}"),
            info_cell(l2, bold=True) if l2 else info_cell(""),
            info_cell(f": {v2 if v2 is not None else ''}") if l2 else info_cell(""),
        ]
        for l1, v1, l2, v2 in info_rows
    ]
    info_table = Table(info_table_data, colWidths=_INFO_COL_WIDTHS)
    info_table.setStyle(TableStyle([
        ("BOX", (0, 0), (-1, -1), 0.9, colors.black),
        ("LINEABOVE", (0, 6), (-1, 6), 0.9, colors.black),
        ("VALIGN", (0, 0), (-1, -1), "TOP"),
        ("TOPPADDING", (0, 0), (-1, -1), 1.0), ("BOTTOMPADDING", (0, 0), (-1, -1), 1.0),
        # Rows 5 and 11 are the last row of each section, sitting right above a rule (the
        # divider, and the outer box bottom). The font's real descent runs past a plain
        # 1pt bottom padding, so the text crowds or crosses the rule below it — give it
        # real clearance instead.
        ("BOTTOMPADDING", (0, 5), (-1, 5), 4.0),
        ("BOTTOMPADDING", (0, 11), (-1, 11), 4.0),
        ("LEFTPADDING", (0, 0), (-1, -1), 4), ("RIGHTPADDING", (0, 0), (-1, -1), 2),
    ]))
    story.append(info_table)
    story.append(Spacer(1, 11.3))

    # ── Earnings / Deductions table ────────────────────────────────────────────────
    def item_rows(items):
        out = []
        for key, label in items:
            scale, amount = row.get(key), row.get(f"{key}_actual")
            if not scale and not amount:
                continue
            out.append((label, _fmt(scale), _fmt(amount)))
        return out

    earning_rows = item_rows(_EARNING_ITEMS)
    deduction_rows = item_rows(_DEDUCTION_ITEMS)
    gross_earning_scale = row.get("gross_earning") or 0
    gross_earning_actual = row.get("gross_earning_actual") or 0
    gross_deduction_scale = row.get("gross_deduction") or 0
    gross_deduction_actual = sum(row.get(f"{k}_actual") or 0 for k, _ in _DEDUCTION_ITEMS)

    label_style = ParagraphStyle("cellLabel", parent=styles["Normal"], fontName=FONT_REGULAR, fontSize=9, leading=10)
    label_style_bold = ParagraphStyle("cellLabelBold", parent=label_style, fontName=FONT_BOLD)
    num_style = ParagraphStyle("cellNum", parent=label_style, alignment=TA_RIGHT)
    num_style_bold = ParagraphStyle("cellNumBold", parent=label_style_bold, alignment=TA_RIGHT)

    def cell_label(text, bold=False):
        # Always a Paragraph, even for "" — see info_cell's comment above; the same
        # default-style fallback would otherwise inflate rows with a blank earnings or
        # deductions side (e.g. CCA, which has no matching deduction that period).
        return Paragraph(text, label_style_bold if bold else label_style)

    def cell_num(text, bold=False):
        return Paragraph(text, num_style_bold if bold else num_style)

    n_rows = max(len(earning_rows), len(deduction_rows))
    ed_data = [[
        cell_label("Earnings", True), cell_num("Scale Rs.", True), cell_num("Amount Rs.", True), cell_label(""), cell_label(""),
        cell_label("Deductions", True), cell_num("Scale Rs.", True), cell_num("Amount Rs.", True),
    ]]
    for i in range(n_rows):
        e = earning_rows[i] if i < len(earning_rows) else ("", "", "")
        d = deduction_rows[i] if i < len(deduction_rows) else ("", "", "")
        ed_data.append([
            cell_label(e[0]), cell_num(e[1]), cell_num(e[2]), cell_label(""), cell_label(""),
            cell_label(d[0]), cell_num(d[1]), cell_num(d[2]),
        ])
    ed_data.append([
        cell_label("Total Earnings", True), cell_num(_fmt(gross_earning_scale), True), cell_num(_fmt(gross_earning_actual), True), cell_label(""), cell_label(""),
        cell_label("Total Deductions", True), cell_num(_fmt(gross_deduction_scale), True), cell_num(_fmt(gross_deduction_actual), True),
    ])

    last_row = len(ed_data) - 1
    ed_table = Table(ed_data, colWidths=_ED_COL_WIDTHS)
    ed_table.setStyle(TableStyle([
        ("BOX", (0, 0), (-1, -1), 0.9, colors.black),
        ("LINEBELOW", (0, 0), (-1, 0), 0.9, colors.black),
        ("LINEABOVE", (0, last_row), (-1, last_row), 0.9, colors.black),
        # Vertical dividers between Description/Scale/Amount on each side, continuous from
        # header through totals, plus the center divider between the Earnings and
        # Deductions halves (column 3, the midpoint of the 11.7pt gutter).
        ("LINEAFTER", (0, 0), (0, -1), 0.9, colors.black),
        ("LINEAFTER", (1, 0), (1, -1), 0.9, colors.black),
        ("LINEAFTER", (3, 0), (3, -1), 0.9, colors.black),
        ("LINEAFTER", (5, 0), (5, -1), 0.9, colors.black),
        ("LINEAFTER", (6, 0), (6, -1), 0.9, colors.black),
        # TOP, not MIDDLE — matters when a label wraps (e.g. TRANSPORT ALLOWANCE): the
        # amount should sit on the same baseline as the label's first line, not centered
        # between both wrapped lines.
        ("VALIGN", (0, 0), (-1, -1), "TOP"),
        ("TOPPADDING", (0, 0), (-1, 0), 1.4), ("BOTTOMPADDING", (0, 0), (-1, 0), 1.4),
        ("TOPPADDING", (0, last_row), (-1, last_row), 1.4), ("BOTTOMPADDING", (0, last_row), (-1, last_row), 1.4),
        ("TOPPADDING", (0, 1), (-1, last_row - 1), 0.1), ("BOTTOMPADDING", (0, 1), (-1, last_row - 1), 0.1),
        # The last body row sits right above the totals-row rule — same descent-crowding
        # issue as the info table's last-row-of-a-section case above.
        ("BOTTOMPADDING", (0, last_row - 1), (-1, last_row - 1), 3.0),
        ("LEFTPADDING", (0, 0), (-1, -1), 4), ("RIGHTPADDING", (0, 0), (-1, -1), 4),
        # The two gutter sub-columns are always blank and only 5.85pt wide — the default
        # padding above would leave them less than 0pt of usable width.
        ("LEFTPADDING", (3, 0), (4, -1), 0), ("RIGHTPADDING", (3, 0), (4, -1), 0),
    ]))
    story.append(ed_table)

    # ── Net pay summary ─────────────────────────────────────────────────────────────
    # No spacer before this — its box sits flush against the earnings/deductions table
    # (matching the reference, where the two read as one continuous bordered block).
    net_pay = row.get("net_amt_payable") or 0
    words = number_to_words_inr(net_pay)
    tds_amount = row.get("tds_actual") or 0
    summary_data = [
        [Paragraph(f"Net Pay : Rs. {_fmt(net_pay)}", net_pay_style)],
        [Paragraph(f"In Words : Rs. {words} Only", net_pay_style)],
        [Paragraph(f"TDS Deducted Upto {_MONTH_NAMES[month]}-{year} : Rs. {_fmt(tds_amount) if tds_amount else 'Nil'}", tds_style)],
        [Paragraph("This is Computer Generated Sheet, does not require Signature.", footer_style)],
    ]
    summary_table = Table(summary_data, colWidths=[_CONTENT_WIDTH])
    summary_table.setStyle(TableStyle([
        ("BOX", (0, 0), (-1, -1), 0.9, colors.black),
        ("LINEBELOW", (0, 1), (-1, 1), 0.9, colors.black),
        ("TOPPADDING", (0, 0), (-1, -1), 0), ("BOTTOMPADDING", (0, 0), (-1, -1), 0),
        ("LEFTPADDING", (0, 0), (-1, -1), 4),
    ]))
    story.append(summary_table)

    BaseDocTemplate.build(doc, story)
    return buf.getvalue()
